import time
import traceback
import argparse

from Audience import Audience


def main(num_audience=None, description=None):
    audience_man = Audience(api_key="AIzaSyDgPvBN0glOm1v7OvXXDZC2rhKQEK6VyWc", 
                        folder="GeneratedImages", 
                        feedback_file_root="GeneratedTexts", 
                        num_audience=num_audience,
                        description=description,)
    while True:
        try:
            print(f">>> GeminiAudience{num_audience} 開始執行")
            audience_man.comment_once()
            time.sleep(5)
        except Exception as e:
            print("\n" + "=" * 60)
            print(f"[ERROR] GeminiAudience{num_audience} 崩潰了，錯誤訊息：")
            traceback.print_exc() # 印出詳細錯誤
            print("=" * 60)
            print(f">>> 5 秒後重啟 GeminiAudience{num_audience}...\n")
            time.sleep(5)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Gemini Audience Monitor")
    parser.add_argument("--audience", type=int, default=2, help="Audience number to monitor")
    parser.add_argument("--description", type=str, default="As an AI audience, how is your feeling when you look at this work generated by AI? Please don't describe yourself.", help="Description the personalized audience will use")
    args = parser.parse_args()

    num_audience = args.audience

    print(f"===== Gemini Audience{num_audience} Monitor 啟動 =====")
    main(num_audience, args.description)
