import time
import traceback
import argparse

from Audience import Audience


def main(num_audience=None, description=None):
    audience_man = Audience(api_key=args.api_key, 
                            folder=args.save_images_folder, 
                            feedback_file_root=args.save_texts_folder, 
                            num_audience=num_audience,
                            description=description,
                            )
    while True:
        try:
            print(f">>> GeminiAudience{num_audience} 開始執行")
            audience_man.comment_once()
            time.sleep(5)
        except Exception as e:
            print("\n" + "=" * 60)
            print(f"[ERROR] GeminiAudience{num_audience} 崩潰了，錯誤訊息：")
            traceback.print_exc() # 印出詳細錯誤
            print("=" * 60)
            print(f">>> 5 秒後重啟 GeminiAudience{num_audience}...\n")
            time.sleep(5)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Gemini Audience Monitor")
    parser.add_argument("--api_key", type=str, default="AIzaSyDgPvBN0glOm1v7OvXXDZC2rhKQEK6VyWc", help="with your actual **Google Gemini API key**")
    parser.add_argument("--save_images_folder", type=str, default="GeneratedImages", help="your GeneratedImages folder")
    parser.add_argument("--save_texts_folder", type=str, default="GeneratedTexts", help="your GeneratedTexts folder")
    parser.add_argument("--audience", type=int, default=1, help="Audience number to monitor")
    parser.add_argument("--description", type=str, default="As an AI audience, how is your feeling when you look at this work generated by AI? Please don't describe yourself.", help="Description the personalized audience will use")
    args = parser.parse_args()

    num_audience = args.audience

    print(f"===== Gemini Audience{num_audience} Monitor 啟動 =====")
    main(num_audience, args.description)
